# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YZLC3niEGaH30TMvPC1SdtRHZmsiPDns
"""

!mkdir -p app

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app/main.py
# from fastapi import FastAPI
# from pydantic import BaseModel
# import pickle
# import re
# 
# app = FastAPI()
# 
# with open("skill_model.pkl", "rb") as f:
#     skill_freq = pickle.load(f)
# 
# class JobDescription(BaseModel):
#     job_description: str
# 
# def extract_skills(text):
#     return re.findall(r'\b[A-Za-z\+\.\#]{2,}\b', text)
# 
# def classify_skill(skill):
#     freq = skill_freq.get(skill.lower(), 0)
#     score = freq / max(skill_freq.values())
#     category = "established" if freq >= 5 else "emerging"
#     return category, round(score, 2)
# 
# @app.post("/skill-trend")
# def detect_skills(data: JobDescription):
#     skills = extract_skills(data.job_description)
#     result = [
#         {"skill": s, "category": classify_skill(s)[0], "trend_score": classify_skill(s)[1]}
#         for s in skills
#     ]
#     return {"detected_skills": result}
#
